title: "Lex von Biedenfeld"
email: alexvonbiedenfeld@gmail.com
description: ""
url: "https://avonbied.github.io"

collections:
  pages:
    output: true
    permalink: /:title:output_ext

defaults: [
    {
      scope: { path: "_pages", type: "pages" },
      values: { layout: "default" }
    },
    {
      scope: { path: "index.html", type: "pages" },
      values: { layout: "default" }
    }
]

markdown: kramdown

source: src/

# include: ["_pages"]

liquid:
  error_mode        : strict
  strict_filters    : true
  strict_variables  : true

permalink: /:year/:month/:title:output_ext

# plugins: [
#   jekyll-octicons,
#   jekyll-github-metadata
# ]

social:
  github: "avonbied"
  linkedin: "avonbied"
  twitter: "avonbied"

strict_front_matter : true

timezone: "America/Chicago"