services:
  gh-page:
    image: node:lts-alpine
    restart: on-failure
    environment:
      - NODE_ENV=production
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app:rw
      # - /home/node/app/.next
    ports:
      - 8001:3000
    command: "yarn start"