name: avonbied-ghpage
services:
  site:
    build: 
      context: app
    restart: on-failure
    ports:
      - 9001:3000
    develop:
      watch:
        - path: app/package.json
          action: rebuild
        - path: app/
          action: sync
          target: /home/node/app