services:
  gh-page:
    build: 
      context: ./app
      args:
        NODE_ENV: development
    restart: on-failure
    networks:
      - frontend
    volumes:
      - ./app:/home/node/app:rw
      - /home/node/app/node_modules
      - /home/node/app/.astro

  runtime:
    image: nginx:alpine-slim
    networks:
      - frontend
    volumes:
      - ./server/default.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - 8080:80
    depends_on:
      - gh-page

networks:
  frontend:
# FROM node:lts-alpine AS build
# WORKDIR /app
# COPY . .
# RUN yarn install
# RUN yarn run build

# FROM httpd:alpine AS runtime
# COPY --from=build /app/dist /usr/local/apache2/htdocs/
# EXPOSE 80