services:
  gh-page:
    build: 
      context: ./app
      args:
        NODE_ENV: development
    restart: on-failure
    ports:
      - 9001:3000
    volumes:
      - ./app:/home/node/app:rw
      - /home/node/app/node_modules
      - /home/node/app/.astro
