name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy-nextjs-gh-pages:
    uses: avonbied/avonbied/.github/workflows/nextjs-gh-pages.yml@main
    with:
      app_dir: ./src