name: CI

on:
	push:
		branches: [ "main" ]
	pull_request:
		branches: [ "main" ]
	workflow_dispatch:

jobs:
	call-workflow-1-in-local-repo:
			uses: avonbied/avonbied/.github/workflows/nextjs-gh-pages.yml@main